config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {:registrations => "users/registrations"}

  get 'my_reports' => "reports#my_reports"
  get 'my_salary' => "salaries#my_salary"

  post 'active_projects' => "projects#active_projects"
  post 'unactive_projects' => "projects#unactive_projects"

  get 'active_projects' => "projects#active_projects"
  get 'unactive_projects' => "projects#unactive_projects"

  post 'make_active' => "projects#make_active"
  post 'make_unactive' => "projects#make_unactive"

  post 'down_rank' => "users#down_rank"
  post 'up_rank' => "users#up_rank"

  post 'current_balance' => "salaries#index"
  post 'total_balance' => "salaries#total_balance"

  post 'make_admin' => "users#make_admin"
  post 'make_user' => "users#back_to_user"

  get 'show_week' => "users#show_week"
  get 'show_month' => "users#show_month"
  get 'show_year' => "users#show_year"

  post 'submit_salary' => "salaries#submit_salary"

  resources :projects

  resources :reports
  resources :salaries

  get 'users', to: 'users#index'

  root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :reports, dependent: :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def make_active
    @project = Project.where("id = ?", params[:project_id]).first
    @project.status = true
    @project.save
    redirect_to :back
  end

  def make_unactive
    @project = Project.where("id = ?", params[:project_id]).first
    @project.status = false
    @project.save
    redirect_to :back
  end

  def active_projects
    @projects = Project.where("status = ?", true)
  end

  def unactive_projects
    @projects = Project.where("status = ?", false)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :status, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project, :html => {:class => "form-horizontal"}) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-lg-4 control-label" %>
    <div class="col-lg-6">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :status, class: "col-lg-4 control-label" %>
    <div class="col-lg-6">
      <%= f.check_box :status %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: "col-lg-4 control-label" %>
    <div class="col-lg-6">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-6 col-md-offset-4">
      <%= f.submit %>
    </div>
  </div>
<% end %>


<style type="text/css">
  #project_status{
    margin-top: 10px;
  }
</style>

app/views/projects/active_projects.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<ul class="nav navbar-nav">
  <li><%= link_to 'All Projects', { :action => "index", :controller => "projects"}, class: "btn btn-default"%></li>
  <li><%= link_to 'Active Projects', { :action => "active_projects", :controller => "projects"},  method: :post, class: "btn btn-default" %></li>
  <li><%= link_to 'Unactive projects', { :action => "unactive_projects", :controller => "projects"},  method: :post, class: "btn btn-default" %></li>
</ul>
<br><br><br>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th>Description</th>
      <th>Change Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.status %></td>
        <td><%= project.description %></td>
        <% if project.status == false %>
        <td><%= link_to 'Make Active', { :action => "make_active", :controller => "projects", :project_id => project.id},  method: :post %></td>
        <% else %>
        <td><%= link_to 'Make Unactive', { :action => "make_unactive", :controller => "projects", :project_id => project.id},  method: :post %></td>
        <% end %>
        <td><%= link_to 'Show', project %></td>
        <% if can? :update, project %>
          <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <% end %>
        <% if can? :destroy, project %>
          <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Project', new_project_path, class: "btn btn-primary" %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<ul class="nav navbar-nav">
  <li><%= link_to 'All Projects', { :action => "index", :controller => "projects"}, class: "btn btn-default"%></li>
  <li><%= link_to 'Active Projects', { :action => "active_projects", :controller => "projects"},  method: :post, class: "btn btn-default" %></li>
  <li><%= link_to 'Unactive projects', { :action => "unactive_projects", :controller => "projects"},  method: :post, class: "btn btn-default" %></li>
</ul>
<br><br><br>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th>Description</th>
      <th>Change Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.status %></td>
        <td><%= project.description %></td>
        <% if project.status == false %>
        <td><%= link_to 'Make Active', { :action => "make_active", :controller => "projects", :project_id => project.id},  method: :post %></td>
        <% else %>
        <td><%= link_to 'Make Unactive', { :action => "make_unactive", :controller => "projects", :project_id => project.id},  method: :post %></td>
        <% end %>
        <td><%= link_to 'Show', project %></td>
        <% if can? :update, project %>
          <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <% end %>
        <% if can? :destroy, project %>
          <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Project', new_project_path, class: "btn btn-primary" %>

app/views/projects/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-default">
        <div class="panel-heading">New Project</div>
          <div class="panel-body">
			<%= render 'form' %>
			 <div class="form-group">
              <div class="col-md-6 col-md-offset-4">
                <%= link_to 'Back', projects_path %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @project.status %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/projects/unactive_projects.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<ul class="nav navbar-nav">
  <li><%= link_to 'All Projects', { :action => "index", :controller => "projects"}, class: "btn btn-default"%></li>
  <li><%= link_to 'Active Projects', { :action => "active_projects", :controller => "projects"},  method: :post, class: "btn btn-default" %></li>
  <li><%= link_to 'Unactive projects', { :action => "unactive_projects", :controller => "projects"},  method: :post, class: "btn btn-default" %></li>
</ul>
<br><br><br>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th>Description</th>
      <th>Change Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.status %></td>
        <td><%= project.description %></td>
          <% if project.status == false %>
          <td><%= link_to 'Make Active', { :action => "make_active", :controller => "projects", :project_id => project.id},  method: :post %></td>
          <% else %>
          <td><%= link_to 'Make Unactive', { :action => "make_unactive", :controller => "projects", :project_id => project.id},  method: :post %></td>
          <% end %>
        <td><%= link_to 'Show', project %></td>
        <% if can? :update, project %>
          <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <% end %>
        <% if can? :destroy, project %>
          <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Project', new_project_path, class: "btn btn-primary"%>