config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {:registrations => "users/registrations"}

  get 'my_reports' => "reports#my_reports"
  get 'my_salary' => "salaries#my_salary"

  post 'active_projects' => "projects#active_projects"
  post 'unactive_projects' => "projects#unactive_projects"

  get 'active_projects' => "projects#active_projects"
  get 'unactive_projects' => "projects#unactive_projects"

  post 'make_active' => "projects#make_active"
  post 'make_unactive' => "projects#make_unactive"

  post 'down_rank' => "users#down_rank"
  post 'up_rank' => "users#up_rank"

  post 'current_balance' => "salaries#index"
  post 'total_balance' => "salaries#total_balance"

  post 'make_admin' => "users#make_admin"
  post 'make_user' => "users#back_to_user"

  get 'show_week' => "users#show_week"
  get 'show_month' => "users#show_month"
  get 'show_year' => "users#show_year"

  post 'submit_salary' => "salaries#submit_salary"

  resources :projects

  resources :reports
  resources :salaries

  get 'users', to: 'users#index'

  root 'projects#index'

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @current_day_report = Report.where("date = ?", report_params[:date])
    if !@current_day_report.present?
      @report = Report.new(report_params)
      @report.user_id = params[:user_id]
      @report.paid = false
      if @report.day_off == true
        @report.time_start = nil
        @report.time_end = nil
        @report.total_time = 0
      else
        @report.total_time = ((@report.time_end - @report.time_start) / 3600).round(2)
      end
      if @report.total_time < 0
        redirect_to :back, flash: {notice: "Wrong time!!!"}
      else
        if @report.total_time > 8
          @report.total_time = 8
        end
        respond_to do |format|
          if @report.save
            format.html { redirect_to @report, notice: 'Report was successfully created.' }
            format.json { render :show, status: :created, location: @report }
          else
            format.html { render :new }
            format.json { render json: @report.errors, status: :unprocessable_entity }
          end
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to :back, error: "An error message for the user" }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    if @report.day_off == true
      @report.time_start = nil
      @report.time_end = nil
      @report.total_time = 0
    else
      @report.total_time = ((@report.time_end - @report.time_start) / 3600).round(2)
    end
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def my_reports
    @reports = Report.where("user_id = ?", current_user.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:comment, :project_id, :user_id, :day_off, :time_start, :time_end, :date)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(@report, :html => {:class => "form-horizontal"}) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :day_off, class: 'col-lg-2 col-md-2 col-sm-2 col-xs-2 control-label' %>
    <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5">
      <div class="checkbox">
        <label>
          <%= f.check_box :day_off %>
        </label>
      </div>
    </div>
  </div>

  <div class="form-group">
      <label class="col-lg-2 control-label">Date</label>
      <div class="col-lg-6">
        <input type="text" class='datepicker form-control'>
      </div>
    </div>

  <div id="date_area">
    <div class="form-group">
      <%= f.label :time_start, class: 'col-lg-2 control-label' %>
      <div class="col-lg-3">
        <%= f.time_select :time_start, class: 'btn-default btn-xs' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :time_end, class: 'col-lg-2 control-label' %>
      <div class="col-lg-3">
        <%= f.time_select :time_end, class: 'btn-default btn-xs' %>
      </div>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :project_id, class: "col-lg-2 control-label" %>
    <div class="col-lg-6">
      <%= select_tag 'report[project_id]', options_from_collection_for_select(Project.where("status = ?", true), 'id', 'name'), class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :comment, class: "col-lg-2 control-label" %>
    <div class="col-lg-6">
      <%= f.text_field :comment, class: "form-control" %>
    </div>
  </div>

  <%= hidden_field( :report, :date) %>
  <%= hidden_field_tag :user_id, current_user.id%>

  <div class="form-group">
    <div class="col-lg-10 col-lg-offset-2">
      <%= f.submit id: "report_submit", class: "btn btn-primary"%>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  $('#report_submit').click(function(){
    var date = $('.datepicker').val()
    $('[name="report[date]"]').val(date);
  });

  $('#report_day_off').change(function() {
    $('#date_area').toggle(!this.checked);
  });

  $('.datepicker').datepicker();

</script>


<style type="text/css">
  #report_time_start_4i, #report_time_start_5i, #report_time_end_4i, #report_time_end_5i{
    margin-top: 5px;
  }
</style>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing All Reports</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Comment</th>
      <th>Project</th>
      <th>User</th>
      <th>Date</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Total Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.comment %></td>
        <td><%= report.project.name %></td>
        <td><%= report.user.first_name %> <%= report.user.last_name %></td>
        <td><%= report.date %></td>
        <% if report.time_start %>
          <td><%= report.time_start.hour %> : <%= report.time_start.min %></td>
        <% else %>
          <td>=//=</td>
        <% end %>
        <% if report.time_end %>
          <td><%= report.time_end.hour %> : <%= report.time_end.min%></td>
        <% else %>
          <td>=//=</td>
        <% end %>
        <% if report.total_time %>
          <td><%= report.total_time %> hr</td>
        <% else %>
          <td>=//=</td>
        <% end %>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/my_reports.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing My Reports</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Comment</th>
      <th>Project</th>
      <th>Date</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Total Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.comment %></td>
        <td><%= report.project.name %></td>
        <td><%= report.date %></td>
        <% if report.time_start %>
          <td><%= report.time_start.hour %> : <%= report.time_start.min %></td>
        <% else %>
          <td>=//=</td>
        <% end %>
        <% if report.time_end %>
          <td><%= report.time_end.hour %> : <%= report.time_end.min%></td>
        <% else %>
          <td>=//=</td>
        <% end %>
        <% if report.total_time %>
          <td><%= report.total_time %> hr</td>
        <% else %>
          <td>=//=</td>
        <% end %>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-default">
        <div class="panel-heading">New Report</div>
          <div class="panel-body">
      			<%= render 'form' %>
      			 <div class="form-group">
              <div class="col-md-6 col-md-offset-4" id="report_back">
                <%= link_to 'Back', reports_path %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<style type="text/css">
  #report_back{
    margin-left: 105px;
  }
</style>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @report.comment %>
</p>

<p>
  <strong>Project:</strong>
  <%= @report.project.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @report.user.first_name %> <%= @report.user.last_name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @report.date %>
</p>

<p>
  <strong>Start Time :</strong>
  <% if @report.time_start%>
  	<%= @report.time_start.hour %> : <%= @report.time_start.min %>
  <% else %>
  	=//=
  <% end %>
</p>

<p>
  <strong>End Time :</strong>
  <% if @report.time_end%>
  	<%= @report.time_end.hour %> : <%= @report.time_end.min %>
  <% else %>
  	=//=
  <% end %>
</p>

<p>
  <strong>Total Time:</strong>
  <% if @report.total_time%>
  	<%= @report.total_time %> hr
  <% else %>
  	=//=
  <% end %>
  
</p>




<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>