config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {:registrations => "users/registrations"}

  get 'my_reports' => "reports#my_reports"
  get 'my_salary' => "salaries#my_salary"

  post 'active_projects' => "projects#active_projects"
  post 'unactive_projects' => "projects#unactive_projects"

  get 'active_projects' => "projects#active_projects"
  get 'unactive_projects' => "projects#unactive_projects"

  post 'make_active' => "projects#make_active"
  post 'make_unactive' => "projects#make_unactive"

  post 'down_rank' => "users#down_rank"
  post 'up_rank' => "users#up_rank"

  post 'current_balance' => "salaries#index"
  post 'total_balance' => "salaries#total_balance"

  post 'make_admin' => "users#make_admin"
  post 'make_user' => "users#back_to_user"

  get 'show_week' => "users#show_week"
  get 'show_month' => "users#show_month"
  get 'show_year' => "users#show_year"

  post 'submit_salary' => "salaries#submit_salary"

  resources :projects

  resources :reports
  resources :salaries

  get 'users', to: 'users#index'

  root 'projects#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GraduateWork</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<nav class="navbar navbar-inverse">
			  <ul class="nav navbar-nav">
				  <% if current_user %>
				  	<li><%= link_to "Projects", projects_path %></li>
				  	<% if can? :read, @reports %>
				  		<li><%= link_to "All Reports", reports_path %></li>
				  		<li><%= link_to "All Salaries", salaries_path %></li>
				  	<% end %>
				  		<li><%= link_to "My Reports", my_reports_path%></li>
				  		<li><%= link_to "My Salary", my_salary_path%></li>
					  <% if can? :read, @users %>
						<li><%= link_to "Users", users_path%></li>
					  <% end %>
				  <% end %>
			  </ul>
			  <ul class="nav nav-pills navbar-right">
					<% if current_user %>
					  <li id="current_user"><%= current_user.first_name %> <%= current_user.last_name %></li>
					  <li class="top_margin"><%= link_to "My Profile", edit_user_registration_path%> </li>
					  <li class="top_margin right-margin"><%= link_to "Sign out", destroy_user_session_path, :method => :delete %> </li>
					<% else %>
					  <li class="top_margin"><%= link_to "Sign up", new_user_registration_path%> </li>
					  <li class="top_margin right-margin"><%= link_to "Sign in", new_user_session_path%> </li>
					<% end %>
		    </ul>
		</nav>
		<%= yield %>
	</div>
</body>
</html>


<style type="text/css">
	.top_margin{
		margin-top: 6px;
	}
	.right-margin{
		margin-right: 13px;
	}
	#current_user{
		color:white;
		margin-top: 15px;
		margin-right: 15px;
	}
</style>